### ISSUE TITLE
Feil i pdf

### ISSUE THREAD

**Issue by TheThalek** [ITK-TTK4235/assignment_4#1]
Yoyo!

På slutten av side 6 står det _"For ˚a prøve ut display kan dere kalle break 15 for ˚a opprette et breakpoint ved
linja dyn_array[i] = i + 1;, etterfulgt av display *dyn_array@5, og til slutt"_, men dette er jo feil. Burde vere 14 <3 Liten feil, men fekk eit par spørsmål om det

**Comment by terjejacobsson** [comment]
Bra sett! Skal fikse ny release straks
